Add rocket detail page
alesrazym/rocket-app pull request #6
Opened 2023-11-06 11:12 UTC by alesrazym

Adds api call, viewmodel, unit test

2023-11-07 09:27 UTC, alesrazym commented
rebased on `detail`

2023-11-14 10:17 UTC, alesrazym commented
rebased on develop

2023-11-14 15:36 UTC, havlisimo requested changes

2023-11-14 15:36 UTC, havlisimo commented on app/src/main/java/cz/quanti/razym/rocketapp/model/Rocket.kt
> +) : Rocket(name, firstFlight, id)
ta dedicnost mi tady prijde zbytecna, naopak bych to spis rozdelil do dvou souboru

2023-11-14 15:36 UTC, havlisimo commented on app/src/main/java/cz/quanti/razym/rocketapp/presentation/RocketDetailViewModel.kt
> +        this.mass["kg"] ?: 0.0, this.firstStage.asStage(), this.secondStage.asStage(),
ty klice ("meters","kg") dej prosim do konstant

2023-11-14 15:36 UTC, havlisimo commented on app/src/main/java/cz/quanti/razym/rocketapp/system/RocketDetailFragment.kt
> +        binding.rocketDetailMass.text = String.format("%.0ft", rocket.massKg / 1000)
ui vrstva by mela obsahovat minimum logiky, takze i tenhle prevod jednotek bych radsi videl ve VM. Klidne se ta property muze jmenovat massTons a vyresit to pri mapovani

2023-11-14 15:36 UTC, havlisimo commented on app/src/main/java/cz/quanti/razym/rocketapp/system/RocketDetailFragment.kt
> +        engines = rocket.secondStage.engines
celkove se snazime minimalizovat pouziti var. V tomto pripade to prida na citelnosti kdyz proste pouzijes `val firstStageEngines` a `val secondStageEngines`

2023-11-14 15:36 UTC, havlisimo commented on app/src/main/java/cz/quanti/razym/rocketapp/system/RocketDetailFragment.kt
> +        // Set the limit, not to flood app when not handled in any kind of clever presentation.
👍

2023-11-14 15:36 UTC, havlisimo commented on app/src/test/java/cz/quanti/razym/rocketapp/presentation/RocketDetailModelTest.kt
> +class RocketDetailModelTest {
```suggestion
class RocketDetailViewModelTest {
```

2023-11-14 15:36 UTC, havlisimo commented on app/src/test/java/cz/quanti/razym/rocketapp/presentation/RocketDetailModelTest.kt
> +        val success = viewModel.uiState.value.state as UiState.Success
je potreba pridat ? jinak dalsi radek kde kontrolujes nullability nedava smysl
```suggestion
        val success = viewModel.uiState.value.state as? UiState.Success
```

2023-11-14 15:36 UTC, havlisimo commented on app/src/test/java/cz/quanti/razym/rocketapp/presentation/RocketDetailModelTest.kt
> +    }
v testech chceme mit co nejjednodussi logiku (idealne zadne for cykly, ify atd.)
```suggestion
        viewModel.fetchRocket(ids[0])
        advanceUntilIdle()
        assertSuccess(viewModel, rocketsData[0].id)

        viewModel.fetchRocket(ids[1])
        advanceUntilIdle()
        assertSuccess(viewModel, rocketsData[1].id)
    }

    private fun createRepository() : RocketsRepository = mockk {
        coEvery { getRocket(ids[0]) } returns flowOf(rocketsData[0])
        coEvery { getRocket(ids[1]) } returns flowOf(rocketsData[1])
        coEvery { getRocket(errorId) } returns flow { throw Exception() }
    }
```
errorId je treba zadefinovat nekde nahore jak mas ten ids list

2023-11-14 21:05 UTC, alesrazym commented
Vyřešil jsem komentáře, `as` jsem místo na `as?` převedl na kontrolu, že to nevyhodí výjimku. Což je možná trochu overkill (výjímkou ten test stejně neprojde), ale beru to jako seznámení se s použitím knihovny. `as?` mi v tomhle případě stejně nedávalo smysl, protože samotná ta null kontrola pak nedávala smysl.

2023-11-21 08:36 UTC, havlisimo approved these changes

2023-11-21 09:11 UTC, merged